<?php
	$emotionListDefault = array(
		array(
                'groupname' => '2233娘', 
                'list' => array(
                    array('type' => 'sticker', 'code' => ':2233:saigao:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/saigao.png'),
                    array('type' => 'sticker', 'code' => ':2233:wuyu:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/wuyu.png'),
                    array('type' => 'sticker', 'code' => ':2233:dead:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/dead.png'),
					array('type' => 'sticker', 'code' => ':2233:weiqu:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/weiqu.png'),
					array('type' => 'sticker', 'code' => ':2233:daku:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/daku.png'),
					array('type' => 'sticker', 'code' => ':2233:yumen:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/yumen.png'),
					array('type' => 'sticker', 'code' => ':2233:wonder22:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/wonder22.png'),
					array('type' => 'sticker', 'code' => ':2233:wonder33:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/wonder33.png'),
					array('type' => 'sticker', 'code' => ':2233:angry:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/angry.png'),
					array('type' => 'sticker', 'code' => ':2233:shock:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/shock.png'),
					array('type' => 'sticker', 'code' => ':2233:liuhan:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/liuhan.png'),
					array('type' => 'sticker', 'code' => ':2233:laugh:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/laugh.png'),
					array('type' => 'sticker', 'code' => ':2233:tea:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/tea.png'),
					array('type' => 'sticker', 'code' => ':2233:ye:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/ye.png'),
					array('type' => 'sticker', 'code' => ':2233:moe:', 'src' => $GLOBALS['assets_path'] . '/stickers/2233/moe.png')
                ),
			),
			array(
                'groupname' => 'kumiko', 
                'list' => array(
                    array('type' => 'sticker', 'code' => ':kumiko:azhe:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/azhe.png'),
                    array('type' => 'sticker', 'code' => ':kumiko:buxie:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/buxie.png'),
                    array('type' => 'sticker', 'code' => ':kumiko:daizhi:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/daizhi.png'),
					array('type' => 'sticker', 'code' => ':kumiko:haomafana:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/haomafana.png'),
					array('type' => 'sticker', 'code' => ':kumiko:jingya:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/jingya.png'),
					array('type' => 'sticker', 'code' => ':kumiko:jingya2:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/jingya2.png'),
					array('type' => 'sticker', 'code' => ':kumiko:jingya3:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/jingya3.png'),
					array('type' => 'sticker', 'code' => ':kumiko:kunrao:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/kunrao.png'),
					array('type' => 'sticker', 'code' => ':kumiko:renzhen:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/renzhen.png'),
					array('type' => 'sticker', 'code' => ':kumiko:tanqi:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/tanqi.png'),
					array('type' => 'sticker', 'code' => ':kumiko:wuyu:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/wuyu.png'),
					array('type' => 'sticker', 'code' => ':kumiko:wuyu2:', 'src' => $GLOBALS['assets_path'] . '/stickers/kumiko/wuyu2.png')
                ),
			),
			array(
                'groupname' => '蛆音娘', 
                'list' => array(
                    array('type' => 'sticker', 'code' => ':quyin:hematemesis:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/hematemesis.png'),
                    array('type' => 'sticker', 'code' => ':quyin:1huaji:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/1huaji.png'),
                    array('type' => 'sticker', 'code' => ':quyin:amazing:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/amazing.png'),
					array('type' => 'sticker', 'code' => ':quyin:angry:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/angry.png'),
					array('type' => 'sticker', 'code' => ':quyin:cry:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/cry.png'),
					array('type' => 'sticker', 'code' => ':quyin:die:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/die.png'),
					array('type' => 'sticker', 'code' => ':quyin:doubt:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/doubt.png'),
					array('type' => 'sticker', 'code' => ':quyin:feizao:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/feizao.png'),
					array('type' => 'sticker', 'code' => ':quyin:fue:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/fue.png'),
					array('type' => 'sticker', 'code' => ':quyin:laughing:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/laughing.png'),
					array('type' => 'sticker', 'code' => ':quyin:look:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/look.png'),
					array('type' => 'sticker', 'code' => ':quyin:maimeng:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/maimeng.png'),
					array('type' => 'sticker', 'code' => ':quyin:OK:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/OK.png'),
					array('type' => 'sticker', 'code' => ':quyin:scare:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/scare.png'),
					array('type' => 'sticker', 'code' => ':quyin:shakinghead:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/shakinghead.png'),
					array('type' => 'sticker', 'code' => ':quyin:sleep:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/sleep.png'),
					array('type' => 'sticker', 'code' => ':quyin:speechless:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/speechless.png'),
					array('type' => 'sticker', 'code' => ':quyin:watermaleon:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/watermaleon.png'),
					array('type' => 'sticker', 'code' => ':quyin:witty:', 'src' => $GLOBALS['assets_path'] . '/stickers/quyin/witty.png')
                ),
			),
			array(
                'groupname' => '原神', 
                'list' => array(
                    array('type' => 'sticker', 'code' => ':genshin:relax:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/relax.png'),
                    array('type' => 'sticker', 'code' => ':genshin:u:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/u.png'),
                    array('type' => 'sticker', 'code' => ':genshin:tangping:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/tangping.png'),
					array('type' => 'sticker', 'code' => ':genshin:o:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/o.png'),
					array('type' => 'sticker', 'code' => ':genshin:daku:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/daku.png'),
					array('type' => 'sticker', 'code' => ':genshin:helpme:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/helpme.png'),
					array('type' => 'sticker', 'code' => ':genshin:jingjue:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/jingjue.png'),
					array('type' => 'sticker', 'code' => ':genshin:makasete:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/makasete.png'),
					array('type' => 'sticker', 'code' => ':genshin:hengheng:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/hengheng.png'),
					array('type' => 'sticker', 'code' => ':genshin:goaway:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/goaway.png'),
					array('type' => 'sticker', 'code' => ':genshin:pigeon:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/pigeon.png'),
					array('type' => 'sticker', 'code' => ':genshin:kanpai:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/kanpai.png'),
					array('type' => 'sticker', 'code' => ':genshin:gohan:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/gohan.png'),
					array('type' => 'sticker', 'code' => ':genshin:chuhuoba:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/chuhuoba.png'),
					array('type' => 'sticker', 'code' => ':genshin:shock:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/shock.png'),
					array('type' => 'sticker', 'code' => ':genshin:stopit:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/stopit.png'),
					array('type' => 'sticker', 'code' => ':genshin:onegai:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/onegai.png'),
					array('type' => 'sticker', 'code' => ':genshin:zzZZ:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/zzZZ.png'),
					array('type' => 'sticker', 'code' => ':genshin:goodjob:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/goodjob.png'),
					array('type' => 'sticker', 'code' => ':genshin:1mora:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/1mora.png'),
					array('type' => 'sticker', 'code' => ':genshin:OK:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/OK.png'),
					array('type' => 'sticker', 'code' => ':genshin:guancha:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/guancha.png'),
					array('type' => 'sticker', 'code' => ':genshin:bixin:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/bixin.png'),
					array('type' => 'sticker', 'code' => ':genshin:shock2:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/shock2.png'),
					array('type' => 'sticker', 'code' => ':genshin:falldown:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/falldown.png'),
					array('type' => 'sticker', 'code' => ':genshin:like:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/like.png'),
					array('type' => 'sticker', 'code' => ':genshin:applaud:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/applaud.png'),
					array('type' => 'sticker', 'code' => ':genshin:guaiqiao:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/guaiqiao.png'),
					array('type' => 'sticker', 'code' => ':genshin:heng:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/heng.png'),
					array('type' => 'sticker', 'code' => ':genshin:indifferent:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/indifferent.png'),
					array('type' => 'sticker', 'code' => ':genshin:tanoshimi:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/tanoshimi.png'),
					array('type' => 'sticker', 'code' => ':genshin:sahua:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/sahua.png'),
					array('type' => 'sticker', 'code' => ':genshin:oyasumi:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/oyasumi.png'),
					array('type' => 'sticker', 'code' => ':genshin:weiqu:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/weiqu.png'),
					array('type' => 'sticker', 'code' => ':genshin:wonder:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/wonder.png'),
					array('type' => 'sticker', 'code' => ':genshin:idea:', 'src' => $GLOBALS['assets_path'] . '/stickers/genshin/idea.png')
                ),
			)
	);
?>